quarkus.log.level=INFO
quarkus.log.file.path=logs/apps.log
quarkus.log.file.enable=true
exchange.api.base-url=https://api.frankfurter.dev
exchange.api.endpoint=/v2/rates
exchange.api.timeout=5000

# ----------------------------
# Retry Configuration
# ----------------------------
mp.fault.tolerance.ResilientExchangeRateClient/getRates/Retry/maxRetries=3
mp.fault.tolerance.ResilientExchangeRateClient/getRates/Retry/delay=200
mp.fault.tolerance.ResilientExchangeRateClient/getRates/Retry/delayUnit=MILLIS

# ----------------------------
# Timeout Configuration
# ----------------------------
mp.fault.tolerance.ResilientExchangeRateClient/getRates/Timeout/value=2000
mp.fault.tolerance.ResilientExchangeRateClient/getRates/Timeout/unit=MILLIS

# ----------------------------
# Circuit Breaker Configuration
# ----------------------------
mp.fault.tolerance.ResilientExchangeRateClient/getRates/CircuitBreaker/requestVolumeThreshold=5
mp.fault.tolerance.ResilientExchangeRateClient/getRates/CircuitBreaker/failureRatio=0.5
mp.fault.tolerance.ResilientExchangeRateClient/getRates/CircuitBreaker/delay=5000
mp.fault.tolerance.ResilientExchangeRateClient/getRates/CircuitBreaker/delayUnit=MILLIS

mp.fault.tolerance.ResilientExchangeRateClient/getRates/CircuitBreaker/successThreshold=2